git:
  pagers:
    - pager: $HOME/.config/lazygit/delta_decode
      colorArg: always
    - pager: delta --paging=never
      colorArg: always
keybinding:
  universal:
    suspendApp: <disabled>
os:
  editPreset: "nvim-remote"
  copyToClipboardCmd: $HOME/.config/lazygit/osc52 {{text}}
