git:
  pagers:
    - pager: $HOME/.config/lazygit/delta_decode
      colorArg: always
    - pager: delta --paging=never
      colorArg: always
keybinding:
  universal:
    suspendApp: <disabled>
os:
  open: "neovide {{filename}} >/dev/null"
